export const experiences = [
  {
    company: "Tech Mahindra",
    role: "Software Engineer",
    duration: "Aug 2024 – Present",
    location: "Hyderabad, India",
    technologies: [
      "Java",
      "Spring Boot",
      "TIBCO BWCE",
      "Flogo",
      "JMS/EMS",
      "PostgreSQL",
      "Oracle",
      "Docker",
      "OpenShift",
      "Elastic",
      "Grafana",
      "REST APIs",
      "SOAP APIs",
      "Microservices",
    ],
    description: [
      "Backend integrations using BWCE and Flogo.",
      "JMS/EMS asynchronous messaging.",
      "PostgreSQL and Oracle integrations.",
      "ActiveSpaces distributed caching.",
      "Docker and OpenShift deployments.",
      "SIT, UAT, Production support.",
      "Onsite migration and go-live activities in Jakarta.",
      "Performance optimization and production troubleshooting.",
    ],
    achievement:
      'Received the "Pat on the Back" award for successfully delivering complex modules under tight deadlines while maintaining high-quality engineering standards.',
  },
  {
    company: "Indosat Ooredoo Hutchison (IOH)",
    role: "Onsite Migration & Go-Live Support",
    duration: "Jakarta, Indonesia",
    location: "Client Site Engagement",
    technologies: [
      "Enterprise Systems",
      "Production Rollout",
      "System Validation",
      "Monitoring",
      "Client Coordination",
      "Deployments",
      "Integration Workflows",
      "Hypercare",
    ],
    description: [
      "Supported migration and go-live activities for the DMP Consolidation platform at IOH.",
      "Worked closely with the engineering and business teams during production readiness validation.",
      "Contributed to Hypercare support and go-live monitoring during critical transition periods.",
      "Ensured smooth operations across migration waves covering 40+ million subscribers.",
      "Collaborated across teams to resolve production issues and validate business-critical flows.",
      "Strengthened offshore-onsite coordination through live client engagement in Jakarta.",
    ],
  },
];